[colors]
draw_bold_text_with_bright_colors = false

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.bright]
black = "0x969896"
blue = "0xb4b7b4"
cyan = "0xa3685a"
green = "0x282a2e"
magenta = "0xe0e0e0"
red = "0xde935f"
white = "0xffffff"
yellow = "0x373b41"

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
Key = "C"
action = "Copy"
mods = "Super"

[[keyboard.bindings]]
Key = "V"
action = "Paste"
mods = "Super"

[[keyboard.bindings]]
Key = "F11"
action = "ToggleFullscreen"

[selection]
save_to_clipboard = false

[window]
opacity = 0.98
